import { createHash } from 'node:crypto';
import { MAX_PROFILE_BYTES, OCR_PROFILE_MARKER, OCR_VERIFICATION_MARKER, parseOcrProfile, parseOcrVerification, parseOcrCatalog } from './ocr_profiles.ts';

export function revisionOf(profile) {
  return createHash('sha256').update(JSON.stringify(parseOcrProfile(profile))).digest('hex');
}
function submission(issue) {
  if (issue.pull_request || issue.user?.type !== 'User' || !Number.isSafeInteger(issue.user?.id) || !Number.isSafeInteger(issue.number)) return null;
  if (issue.labels?.some((label) => (typeof label === 'string' ? label : label.name) === 'hidden') || (issue.state === 'closed' && issue.state_reason === 'not_planned')) return null;
  const body = typeof issue.body === 'string' ? issue.body.trim() : '';
  const kind = body.startsWith(OCR_PROFILE_MARKER) ? 'profile' : body.startsWith(OCR_VERIFICATION_MARKER) ? 'verification' : null;
  if (!kind) return null;
  if (Buffer.byteLength(body) > MAX_PROFILE_BYTES + 1024) throw new Error('Submission is too large.');
  const marker = kind === 'profile' ? OCR_PROFILE_MARKER : OCR_VERIFICATION_MARKER;
  const match = /^\s*```json\s*\n([\s\S]*?)\n```\s*$/u.exec(body.slice(marker.length));
  if (!match) throw new Error('Keep the marker and exactly one JSON code block generated by GSM.');
  let data;
  try { data = JSON.parse(match[1]); } catch { throw new Error('The JSON is invalid. Export it from GSM again.'); }
  try { return { kind, data: kind === 'profile' ? parseOcrProfile(data) : parseOcrVerification(data) }; }
  catch { throw new Error('The configuration has unsupported fields, values, coordinates, or a schema version. Export it from the current GSM version.'); }
}

export function compileCatalog(issues) {
  const profiles = new Map(), reports = [], outcomes = new Map(), authors = new Map();
  for (const issue of issues) {
    try {
      const parsed = submission(issue);
      if (!parsed) continue;
      if (parsed.kind === 'profile') {
        const id = `profile-${issue.number}`;
        profiles.set(id, { id, revision: revisionOf(parsed.data), author: issue.user.login, issueNumber: issue.number, updatedAt: issue.updated_at,
          profile: parsed.data, verification: { works: 0, needsWork: 0 } });
        authors.set(id, issue.user.id);
        outcomes.set(issue.number, { status: 'published', id });
      } else reports.push({ issue, report: parsed.data });
    } catch (error) { outcomes.set(issue.number, { status: 'invalid', message: error.message }); }
  }
  const latest = new Map();
  for (const { issue, report } of reports) {
    const entry = profiles.get(report.profileId);
    if (!entry || entry.revision !== report.revision) {
      outcomes.set(issue.number, { status: 'stale' }); continue;
    }
    if (authors.get(report.profileId) === issue.user.id) {
      outcomes.set(issue.number, { status: 'invalid', message: 'Authors cannot verify their own configuration. Independent reports are counted.' }); continue;
    }
    const key = `${report.profileId}:${issue.user.id}`;
    const previous = latest.get(key);
    if (!previous || issue.updated_at > previous.issue.updated_at || (issue.updated_at === previous.issue.updated_at && issue.number > previous.issue.number)) latest.set(key, { issue, report });
    outcomes.set(issue.number, { status: 'verified', id: entry.id });
  }
  for (const { report } of latest.values()) profiles.get(report.profileId).verification[report.result]++;
  const catalog = parseOcrCatalog({ schemaVersion: 1, generatedAt: new Date().toISOString(), profiles: [...profiles.values()].sort((a, b) => a.issueNumber - b.issueNumber) });
  if (Buffer.byteLength(JSON.stringify(catalog, null, 2)) > 9 * 1024 * 1024) throw new Error('Catalog exceeds the supported size; split the catalog before publishing.');
  return { catalog, outcomes };
}
